- text: '# Manual Pantheon Project'
- text: "This is a brief overview of my manual Pantheon Project located at https://github.com/fourkitchens/readmes/tree/master/pantheon/d7/manual"
- include: '../../pantheon/d7/manual/at-a-glance.md'
- include: '../../pantheon/d7/manual/brief-foundation-architecture.md'
- include: '../../pantheon/d7/manual/before-you-start.md'
- include: '../../global/getting-started.md'
- include: '../../global/subsequent-builds.md'
- include: '../../global/git-workflow.md'
- include: '../../global/prs.md'
- include: '../../global/commits.md'
- include: '../../pantheon/d7/manual/configuration-management-workflow.md'
- include: '../../pantheon/d7/manual/deployment.md'
- include: '../../global/testing.md'
- include: '../../global/known-issues.md'
